import { chromium } from "playwright-core";
import { sessionCookie } from "./session.mjs";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "es-ES" });
await ctx.addCookies([sessionCookie(process.env.USER_ID)]);
const page = await ctx.newPage();
const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.on("console", (m) => m.type() === "error" && errors.push(m.text()));
const base = "http://localhost:3100";
const text = async () => { await page.waitForSelector("h1", { timeout: 8000 }); await page.waitForTimeout(700); return (await page.locator("main").innerText()).replace(/\s+/g, " "); };
await page.goto(base + "/tareas?v=todas");
console.log("antes:", (await text()).match(/Pagar autónomos[^A-Z]*/)?.[0]);
await page.getByRole("checkbox", { name: /pagar autónomos/i }).click(); await page.waitForTimeout(1500);
await page.goto(base + "/tareas?v=todas");
console.log("tras completar (debe salir 20/11/2026):", (await text()).match(/Pagar autónomos[^A-Z]*/)?.[0]);
await page.goto(base + "/tareas?v=hechas");
console.log("hechas:", (await text()).includes("Pagar autónomos") ? "ok" : "falta");
await page.goto(base + "/tareas?v=todas");
await page.getByRole("checkbox", { name: /pagar autónomos/i }).click(); await page.waitForTimeout(600);
await page.getByRole("button", { name: "Deshacer" }).click(); await page.waitForTimeout(1500);
await page.goto(base + "/tareas?v=todas");
const t = await text();
console.log("tras deshacer:", (t.match(/Pagar autónomos[^A-Z]*/g)));
console.log("errores:", JSON.stringify(errors));
await browser.close();
